name: upkeep_plus

description: UPkeep+ is Booking Services app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  http: ^0.13.5
  get_it: ^7.3.0
  smooth_page_indicator: ^1.0.1
  flutter_verification_code: ^1.1.6
  flutter_bloc: ^8.1.2
  intl: ^0.18.1
  shared_preferences: ^2.1.1
  cached_network_image: ^3.2.3
  auto_size_text: ^3.0.0
  flutter_rating_bar: ^4.0.1
  provider: ^6.0.5
  flutter_native_splash: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo1.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"


flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
